<h2>Import</h2>

In [1]:
import numpy as np
import pandas as pd
import datetime

<h2>Exploring your data</h2>

<h3>Read raw data from file</h3>

In [2]:
raw_df = pd.DataFrame()
raw_df=pd.read_csv('data_footballer.csv')

In [3]:
# TEST
raw_df.head()

,Name,Height,Weight,Preferred Foot,Birth Date,Age,Preferred Positions,OVR,POT,Value,...,Long Shots,Curve,FK Acc.,Penalties,Volleys,GK Positioning,GK Diving,GK Handling,GK Kicking,GK Reflexes
0,Erling Haaland,195 cm,94 kg,Left,"July 21, 2000",23,ST,91,94,157.000.000,...,86,77,62,84,90,11,7,14,13,7
1,Kylian Mbappé,182 cm,75 kg,Right,"Dec. 20, 1998",24,"ST, LW",91,94,153.500.000,...,83,80,69,84,85,11,13,5,7,6
2,Kevin De Bruyne,181 cm,75 kg,Right,"June 28, 1991",32,"CM, CAM",91,91,103.000.000,...,92,92,83,83,83,10,15,13,5,13
3,Harry Kane,188 cm,85 kg,Right,"July 28, 1993",30,ST,90,90,119.500.000,...,87,82,65,92,89,14,8,10,11,11
4,Thibaut Courtois,199 cm,96 kg,Left,"May 11, 1992",31,GK,90,90,63.000.000,...,17,19,20,27,12,90,85,89,76,93

<h3>How many rows and how many columns does the raw data have?</h3>

In [4]:
rows=len(raw_df.axes[0])
cols=len(raw_df.axes[1])
shape=(rows,cols)
print(f"Current shape: {shape}")

Current shape: (2970, 45)

<h3>What data type does each column currently have? Are there any columns whose data types are not suitable for further processing?</h3>

<h4>Convert all columns into their correct datatype before doing anything else</h4>

In [5]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2970 entries, 0 to 2969
Data columns (total 45 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 2970 non-null   object
 1   Height               2970 non-null   object
 2   Weight               2970 non-null   object
 3   Preferred Foot       2970 non-null   object
 4   Birth Date           2970 non-null   object
 5   Age                  2970 non-null   int64
 6   Preferred Positions  2970 non-null   object
 7   OVR                  2970 non-null   int64
 8   POT                  2970 non-null   int64
 9   Value                2970 non-null   object
 10  Wage                 2970 non-null   object
 11  Ball Control         2970 non-null   int64
 12  Dribbling            2970 non-null   int64
 13  Marking              2970 non-null   object
 14  Slide Tackle         2970 non-null   int64
 15  Stand Tackle         2970 non-null   int64
 16  Aggression           2970 non-null   int64
 17  Reactions            2970 non-null   int64
 18  Att. Position        2970 non-null   int64
 19  Interceptions        2970 non-null   int64
 20  Vision               2970 non-null   int64
 21  Composure            2970 non-null   int64
 22  Crossing             2970 non-null   int64
 23  Short Pass           2970 non-null   int64
 24  Long Pass            2970 non-null   int64
 25  Acceleration         2970 non-null   int64
 26  Stamina              2970 non-null   int64
 27  Strength             2970 non-null   int64
 28  Balance              2970 non-null   int64
 29  Sprint Speed         2970 non-null   int64
 30  Agility              2970 non-null   int64
 31  Jumping              2970 non-null   int64
 32  Heading              2970 non-null   int64
 33  Shot Power           2970 non-null   int64
 34  Finishing            2970 non-null   int64
 35  Long Shots           2970 non-null   int64
 36  Curve                2970 non-null   int64
 37  FK Acc.              2970 non-null   int64
 38  Penalties            2970 non-null   int64
 39  Volleys              2970 non-null   int64
 40  GK Positioning       2970 non-null   int64
 41  GK Diving            2970 non-null   int64
 42  GK Handling          2970 non-null   int64
 43  GK Kicking           2970 non-null   int64
 44  GK Reflexes          2970 non-null   int64
dtypes: int64(36), object(9)
memory usage: 1.0+ MB

Column `Birth Date` should be converted to datetime.

In [6]:
cols_change=['Value','Wage', 'Marking']
raw_df['Value'] = raw_df['Value'].str.replace('.','')
raw_df[cols_change] = raw_df[cols_change].apply(pd.to_numeric, errors='coerce')
raw_df['Birth Date'] = raw_df['Birth Date'].str.replace('.','').str.replace('Sept', 'Sep')
converted_dates = []
for i in range(len(raw_df['Birth Date'])):
    try:
        converted_dates.append(pd.to_datetime(raw_df['Birth Date'].iloc[i], format='%b %d, %Y'))
    except ValueError:
        converted_dates.append(pd.to_datetime(raw_df['Birth Date'].iloc[i], format='%B %d, %Y'))

raw_df['Birth Date'] = converted_dates

/tmp/ipykernel_1899/1542770264.py:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  raw_df['Value'] = raw_df['Value'].str.replace('.','')
/tmp/ipykernel_1899/1542770264.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  raw_df['Birth Date'] = raw_df['Birth Date'].str.replace('.','').str.replace('Sept', 'Sep')

Column **Height** and **Weight** should be converted to int. This help analyze easier. We will delete unit at last of each element these columns

In [ ]:
raw_df['Height'] = raw_df['Height'].str.rstrip(' cm').astype(int)
raw_df['Weight'] = raw_df['Weight'].str.rstrip(' kg').astype(int)

In [7]:
# TEST
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2970 entries, 0 to 2969
Data columns (total 45 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 2970 non-null   object
 1   Height               2970 non-null   object
 2   Weight               2970 non-null   object
 3   Preferred Foot       2970 non-null   object
 4   Birth Date           2970 non-null   datetime64[ns]
 5   Age                  2970 non-null   int64
 6   Preferred Positions  2970 non-null   object
 7   OVR                  2970 non-null   int64
 8   POT                  2970 non-null   int64
 9   Value                2947 non-null   float64
 10  Wage                 2947 non-null   float64
 11  Ball Control         2970 non-null   int64
 12  Dribbling            2970 non-null   int64
 13  Marking              0 non-null      float64
 14  Slide Tackle         2970 non-null   int64
 15  Stand Tackle         2970 non-null   int64
 16  Aggression           2970 non-null   int64
 17  Reactions            2970 non-null   int64
 18  Att. Position        2970 non-null   int64
 19  Interceptions        2970 non-null   int64
 20  Vision               2970 non-null   int64
 21  Composure            2970 non-null   int64
 22  Crossing             2970 non-null   int64
 23  Short Pass           2970 non-null   int64
 24  Long Pass            2970 non-null   int64
 25  Acceleration         2970 non-null   int64
 26  Stamina              2970 non-null   int64
 27  Strength             2970 non-null   int64
 28  Balance              2970 non-null   int64
 29  Sprint Speed         2970 non-null   int64
 30  Agility              2970 non-null   int64
 31  Jumping              2970 non-null   int64
 32  Heading              2970 non-null   int64
 33  Shot Power           2970 non-null   int64
 34  Finishing            2970 non-null   int64
 35  Long Shots           2970 non-null   int64
 36  Curve                2970 non-null   int64
 37  FK Acc.              2970 non-null   int64
 38  Penalties            2970 non-null   int64
 39  Volleys              2970 non-null   int64
 40  GK Positioning       2970 non-null   int64
 41  GK Diving            2970 non-null   int64
 42  GK Handling          2970 non-null   int64
 43  GK Kicking           2970 non-null   int64
 44  GK Reflexes          2970 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(36), object(5)
memory usage: 1.0+ MB

<h3>Check missing value and solve missing value in data</h3>

In [8]:
missing_ratio=(raw_df.isnull().sum()/len(raw_df)*100).round(2)
missing_ratio

Name                     0.00
Height                   0.00
Weight                   0.00
Preferred Foot           0.00
Birth Date               0.00
Age                      0.00
Preferred Positions      0.00
OVR                      0.00
POT                      0.00
Value                    0.77
Wage                     0.77
Ball Control             0.00
Dribbling                0.00
Marking                100.00
Slide Tackle             0.00
Stand Tackle             0.00
Aggression               0.00
Reactions                0.00
Att. Position            0.00
Interceptions            0.00
Vision                   0.00
Composure                0.00
Crossing                 0.00
Short Pass               0.00
Long Pass                0.00
Acceleration             0.00
Stamina                  0.00
Strength                 0.00
Balance                  0.00
Sprint Speed             0.00
Agility                  0.00
Jumping                  0.00
Heading                  0.00
Shot Power               0.00
Finishing                0.00
Long Shots               0.00
Curve                    0.00
FK Acc.                  0.00
Penalties                0.00
Volleys                  0.00
GK Positioning           0.00
GK Diving                0.00
GK Handling              0.00
GK Kicking               0.00
GK Reflexes              0.00
dtype: float64

If the percentage of missing values is greater than 75%, the column is dropped from the dataframe.

In [9]:
for i in missing_ratio.keys():
    if missing_ratio[i]>75.0:
        raw_df=raw_df.drop(columns=[i])

In [10]:
# TEST
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2970 entries, 0 to 2969
Data columns (total 44 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 2970 non-null   object
 1   Height               2970 non-null   object
 2   Weight               2970 non-null   object
 3   Preferred Foot       2970 non-null   object
 4   Birth Date           2970 non-null   datetime64[ns]
 5   Age                  2970 non-null   int64
 6   Preferred Positions  2970 non-null   object
 7   OVR                  2970 non-null   int64
 8   POT                  2970 non-null   int64
 9   Value                2947 non-null   float64
 10  Wage                 2947 non-null   float64
 11  Ball Control         2970 non-null   int64
 12  Dribbling            2970 non-null   int64
 13  Slide Tackle         2970 non-null   int64
 14  Stand Tackle         2970 non-null   int64
 15  Aggression           2970 non-null   int64
 16  Reactions            2970 non-null   int64
 17  Att. Position        2970 non-null   int64
 18  Interceptions        2970 non-null   int64
 19  Vision               2970 non-null   int64
 20  Composure            2970 non-null   int64
 21  Crossing             2970 non-null   int64
 22  Short Pass           2970 non-null   int64
 23  Long Pass            2970 non-null   int64
 24  Acceleration         2970 non-null   int64
 25  Stamina              2970 non-null   int64
 26  Strength             2970 non-null   int64
 27  Balance              2970 non-null   int64
 28  Sprint Speed         2970 non-null   int64
 29  Agility              2970 non-null   int64
 30  Jumping              2970 non-null   int64
 31  Heading              2970 non-null   int64
 32  Shot Power           2970 non-null   int64
 33  Finishing            2970 non-null   int64
 34  Long Shots           2970 non-null   int64
 35  Curve                2970 non-null   int64
 36  FK Acc.              2970 non-null   int64
 37  Penalties            2970 non-null   int64
 38  Volleys              2970 non-null   int64
 39  GK Positioning       2970 non-null   int64
 40  GK Diving            2970 non-null   int64
 41  GK Handling          2970 non-null   int64
 42  GK Kicking           2970 non-null   int64
 43  GK Reflexes          2970 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(36), object(5)
memory usage: 1021.1+ KB

After remove features which have large missing values, our dataframe still have missing values. So that, we need to fill these missing values so that they can be used in analysis.

In [11]:
# Với 2 cột Value và Wage điền giá trị NaN bằng trung bình của hai giá trị bên cạnh
raw_df['Value'] = raw_df['Value'].fillna((raw_df['Value'].shift() + raw_df['Value'].shift(-1)) / 2)
raw_df['Wage'] = raw_df['Wage'].fillna((raw_df['Wage'].shift() + raw_df['Wage'].shift(-1)) / 2)
# Hiển thị DataFrame sau khi điền giá trị NaN
display(raw_df)

,Name,Height,Weight,Preferred Foot,Birth Date,Age,Preferred Positions,OVR,POT,Value,...,Long Shots,Curve,FK Acc.,Penalties,Volleys,GK Positioning,GK Diving,GK Handling,GK Kicking,GK Reflexes
0,Erling Haaland,195 cm,94 kg,Left,2000-07-21,23,ST,91,94,157000000.0,...,86,77,62,84,90,11,7,14,13,7
1,Kylian Mbappé,182 cm,75 kg,Right,1998-12-20,24,"ST, LW",91,94,153500000.0,...,83,80,69,84,85,11,13,5,7,6
2,Kevin De Bruyne,181 cm,75 kg,Right,1991-06-28,32,"CM, CAM",91,91,103000000.0,...,92,92,83,83,83,10,15,13,5,13
3,Harry Kane,188 cm,85 kg,Right,1993-07-28,30,ST,90,90,119500000.0,...,87,82,65,92,89,14,8,10,11,11
4,Thibaut Courtois,199 cm,96 kg,Left,1992-05-11,31,GK,90,90,63000000.0,...,17,19,20,27,12,90,85,89,76,93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2965,Mohamed-Ali Cho,181 cm,66 kg,Left,2004-01-19,19,"ST, RM",72,83,2600000.0,...,65,43,50,64,52,7,9,6,6,7
2966,Boško Šutalo,188 cm,72 kg,Right,2000-01-01,23,CB,72,77,2400000.0,...,40,41,29,47,30,11,13,14,14,5
2967,Fabricio Díaz,176 cm,69 kg,Right,2003-02-03,20,"CM, CDM",72,83,2600000.0,...,70,59,61,72,75,12,6,11,11,6
2968,Federico Pereira,187 cm,81 kg,Right,2000-02-24,23,"CB, RB",72,82,2400000.0,...,41,49,45,45,37,12,11,8,9,12
2969,Santiago Rodríguez,172 cm,62 kg,Right,2000-01-08,23,"CAM, LM, CF",72,81,2700000.0,...,61,57,53,56,51,10,11,8,6,12

In [12]:
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2970 entries, 0 to 2969
Data columns (total 44 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 2970 non-null   object
 1   Height               2970 non-null   object
 2   Weight               2970 non-null   object
 3   Preferred Foot       2970 non-null   object
 4   Birth Date           2970 non-null   datetime64[ns]
 5   Age                  2970 non-null   int64
 6   Preferred Positions  2970 non-null   object
 7   OVR                  2970 non-null   int64
 8   POT                  2970 non-null   int64
 9   Value                2970 non-null   float64
 10  Wage                 2970 non-null   float64
 11  Ball Control         2970 non-null   int64
 12  Dribbling            2970 non-null   int64
 13  Slide Tackle         2970 non-null   int64
 14  Stand Tackle         2970 non-null   int64
 15  Aggression           2970 non-null   int64
 16  Reactions            2970 non-null   int64
 17  Att. Position        2970 non-null   int64
 18  Interceptions        2970 non-null   int64
 19  Vision               2970 non-null   int64
 20  Composure            2970 non-null   int64
 21  Crossing             2970 non-null   int64
 22  Short Pass           2970 non-null   int64
 23  Long Pass            2970 non-null   int64
 24  Acceleration         2970 non-null   int64
 25  Stamina              2970 non-null   int64
 26  Strength             2970 non-null   int64
 27  Balance              2970 non-null   int64
 28  Sprint Speed         2970 non-null   int64
 29  Agility              2970 non-null   int64
 30  Jumping              2970 non-null   int64
 31  Heading              2970 non-null   int64
 32  Shot Power           2970 non-null   int64
 33  Finishing            2970 non-null   int64
 34  Long Shots           2970 non-null   int64
 35  Curve                2970 non-null   int64
 36  FK Acc.              2970 non-null   int64
 37  Penalties            2970 non-null   int64
 38  Volleys              2970 non-null   int64
 39  GK Positioning       2970 non-null   int64
 40  GK Diving            2970 non-null   int64
 41  GK Handling          2970 non-null   int64
 42  GK Kicking           2970 non-null   int64
 43  GK Reflexes          2970 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(36), object(5)
memory usage: 1021.1+ KB

<h3>Group feature</h3>

`raw_df` have so many columnns, that make them distracted to analyze.  
To further streamline the dataset and improve analytical focus, consider merging related columns into cohesive groups, such as **'Ball Skills,' 'Defence,' 'Mental,' 'Passing,' 'Physical,' 'Shooting,' and 'Goalkeeper.'**
This grouping approach enhances the organization of the data, making it more accessible and facilitating a more insightful analysis of player performance.

In [13]:
raw_df['Ball Skills']=(raw_df['Ball Control']+raw_df['Dribbling'])/2
raw_df['Defence']=(raw_df['Slide Tackle']+raw_df['Stand Tackle'])/2
raw_df['Mental'] = raw_df.loc[:,'Aggression':'Composure'].mean(axis=1)
raw_df['Passing'] = raw_df.loc[:,'Crossing':'Long Pass'].mean(axis=1)
raw_df['Physical'] = raw_df.loc[:,'Acceleration':'Jumping'].mean(axis=1)
raw_df['Shooting'] = raw_df.loc[:,'Heading':'Volleys'].mean(axis=1)
raw_df['Goalkeeper'] = raw_df.loc[:,'GK Positioning':'GK Reflexes'].mean(axis=1)
raw_df.drop(columns=raw_df.columns[11:43], inplace=True)

In [14]:
raw_df = round(raw_df, 1)
raw_df

,Name,Height,Weight,Preferred Foot,Birth Date,Age,Preferred Positions,OVR,POT,Value,Wage,GK Reflexes,Ball Skills,Defence,Mental,Passing,Physical,Shooting,Goalkeeper
0,Erling Haaland,195 cm,94 kg,Left,2000-07-21,23,ST,91,94,157000000.0,340.0,7,80.5,38.0,80.2,59.0,83.7,84.0,10.4
1,Kylian Mbappé,182 cm,75 kg,Right,1998-12-20,24,"ST, LW",91,94,153500000.0,225.0,6,92.5,33.0,76.7,78.3,89.0,82.2,8.4
2,Kevin De Bruyne,181 cm,75 kg,Right,1991-06-28,32,"CM, CAM",91,91,103000000.0,350.0,13,89.0,61.5,84.0,94.3,75.7,83.1,11.2
3,Harry Kane,188 cm,85 kg,Right,1993-07-28,30,ST,90,90,119500000.0,170.0,11,84.5,42.0,81.3,85.0,75.9,86.5,10.8
4,Thibaut Courtois,199 cm,96 kg,Left,1992-05-11,31,GK,90,90,63000000.0,250.0,93,18.0,17.0,41.5,27.3,54.0,22.4,86.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2965,Mohamed-Ali Cho,181 cm,66 kg,Left,2004-01-19,19,"ST, RM",72,83,2600000.0,13.5,7,78.5,21.0,54.0,61.7,71.0,60.1,7.0
2966,Boško Šutalo,188 cm,72 kg,Right,2000-01-01,23,CB,72,77,2400000.0,9.7,5,62.5,71.5,60.3,61.7,63.6,44.9,11.4
2967,Fabricio Díaz,176 cm,69 kg,Right,2003-02-03,20,"CM, CDM",72,83,2600000.0,9.2,6,71.0,73.0,68.3,67.3,73.6,66.5,9.2
2968,Federico Pereira,187 cm,81 kg,Right,2000-02-24,23,"CB, RB",72,82,2400000.0,9.7,12,61.0,71.0,57.0,62.7,75.1,48.0,10.4
2969,Santiago Rodríguez,172 cm,62 kg,Right,2000-01-08,23,"CAM, LM, CF",72,81,2700000.0,5.6,12,73.5,36.5,61.0,67.3,69.1,55.8,9.4

<h3>What does each line mean? Does it matter if the lines have different meanings?</h3>

Each line in the provided data represents information about a specific player in a football (soccer) context.  

These lines provide a comprehensive overview of each player's characteristics and abilities. The differences in meanings among the lines are expected and reflect the diversity of player positions, attributes, and roles within a football team. The dataset captures a range of player types, from strikers (ST) and midfielders (CM, CAM) to goalkeepers (GK), each with their own set of skills and attributes. 

Analyzing this data allows for comparisons between players, understanding their strengths and weaknesses, and making informed decisions, such as scouting or selecting players for specific positions on a team.

<h3>Does the raw data have duplicate rows?</h3>

In [15]:
num_duplicated_rows = None
dupli=raw_df.duplicated()
count=0
for i in dupli:
    if i == True:
        count+=1
num_duplicated_rows=count

In [16]:
# TEST
if num_duplicated_rows == 0:
    print(f"Your raw data have no duplicated line.!")
else:
    if num_duplicated_rows > 1:
        ext = "lines"
    else:
        ext = "line"
    print(f"Your raw data have {num_duplicated_rows} duplicated " + ext + ". Please de-deduplicate your raw data.!")

Your raw data have no duplicated line.!

In [17]:
# De-deduplicate raw data
raw_df=raw_df.drop_duplicates()

<h3>What does each column mean?</h3>

<div>
    
**Height**: The player's height.
    
**Weight**: The player's weight.

**Preferred Foot**: The foot that the player prefers to use (Left or Right).

**Birth Date**: The player's date of birth.Age: The player's current age.

**Preferred Positions**: The positions on the field that the player prefers to play.

**OVR (Overall)**: The player's overall skill level or rating.

**POT (Potential)**: The player's potential skill level or rating.

**Value**: The estimated market value of the player.

**Wage**: The player's weekly wage.

**Ball Skills**: Composite score representing ball control and dribbling skills.

**Defence**: Composite score representing defensive skills, combining slide tackle and stand tackle.

**Mental**: The average of attributes related to mental skills (Aggression to Composure).

**Passing**: The average of attributes related to passing skills (Crossing to Long Pass).

**Physical**: The average of attributes related to physical skills (Acceleration to Jumping).

**Shooting**: The average of attributes related to shooting skills (Heading to Volleys).

**Goalkeeper**: The average of attributes related to goalkeeping skills.
</div>

<h3>Save your processed data</h3>

In [18]:
raw_df.to_csv("data_footballer_processed.csv", index=False)